### PR TITLE
docker: pin base image versions

### LINKED ISSUE #21: no output plots
As mentioned IRL, the example stopped producing plots if one rebuilds images and reruns the example from scratch using vanilla ``yadage``.  (I.e. also outside of REANA.)

How to reproduce:

```console
$ docker rmi atlas/analysisbase
$ cd eventselection
$ docker build -t reanahub/reana-demo-atlas-recast-eventselection . --no-cache
$ cd ../statanalysis
$ docker build -t reanahub/reana-demo-atlas-recast-statanalysis .
$ cd ..
$ mkvirtualenv yadage27 -p /usr/bin/python2.7
$ yadage-run _run workflow/workflow.yml ./workflow/test_inputs/inp1.yml
```

The ROOT files were produced:

```console
$ find _run | grep root
_run/eventselection/submitDir/input/sample.root
_run/eventselection/submitDir/hist-sample.root
_run/eventselection/submitDir/hist/sample.root
_run/eventselection/submitDir/driver.root
```

as well as the JSON fit results:

```console
$ find _run | grep limit
_run/statanalysis/fitresults/limit_data.json
_run/statanalysis/fitresults/limit_data_nomsignal.json
```

but no plots:

```
$ find _run | grep png
```

The statanalysis logs show that:

```console
$ tail -10 _run/statanalysis/_packtivity/statanalysis.run.log
2019-11-28 11:38:51,883 | pack.statanalysis.ru |   INFO | NO.   NAME      VALUE            ERROR          SIZE      DERIVATIVE
2019-11-28 11:38:51,883 | pack.statanalysis.ru |   INFO | 1  alpha_syst1  -7.70828e-01   9.50708e-01   4.66492e-03  -4.71670e-03
2019-11-28 11:38:51,883 | pack.statanalysis.ru |   INFO | ERR DEF= 0.5
2019-11-28 11:38:51,884 | pack.statanalysis.ru |   INFO | AsymptoticCalculator::EvaluateNLL -  value = -1210.79 for poi fixed at = 2    fit time : Real time 0:00:00, CP time 0.000
2019-11-28 11:38:51,884 | pack.statanalysis.ru |   INFO | [#0] PROGRESS:Eval --          ASIMOV data qmu_A = 16.9355 condNLL = -1210.79 uncond -1219.26
2019-11-28 11:38:51,884 | pack.statanalysis.ru |   INFO | [#0] PROGRESS:Eval -- poi = 2 qmu = 9.06996 qmu_A = 16.9355 sigma = 0.485994  CLsplusb = 0.00129921 CLb = 0.865125 CLs = 665.885
2019-11-28 11:38:51,918 | pack.statanalysis.ru |   INFO | cling::DynamicLibraryManager::loadLibrary(): libtiff.so.5: cannot open shared object file: No such file or directory
2019-11-28 11:38:51,918 | pack.statanalysis.ru |   INFO | Error in <TInterpreter::TCling::AutoLoad>: failure loading library libASImage.so for TASImage
2019-11-28 11:38:51,919 | pack.statanalysis.ru |   INFO | cling::DynamicLibraryManager::loadLibrary(): libtiff.so.5: cannot open shared object file: No such file or directory
2019-11-28 11:38:52,092 | pack.statanalysis.ru |   INFO | 0.5 0.574709475331
```

Note the libtiff troubles.

@lukasheinrich :

(1) Is the code of the example recent and how you would like it to look? Perhaps there were some changes on the ATLAS base image side that were not propagated to the REANA repo?

(2) Can we pin the base image and all free dependencies to some particular versions?  The example uses currently the `latest` base image:

```
eventselection/Dockerfile:1:FROM atlas/analysisbase:latest
statanalysis/Dockerfile:1:FROM atlas/analysisbase
```

as well as ian unpinned ``htfools`` library:

```
statanalysis/Dockerfile:3:RUN sudo sh -c "source /home/atlas/release_setup.sh && pip install hftools"
```

This is prone to failing sooner or later... For a nicely complete analysis preservation example, it would be good to use pinned versions of all dependencies.

Can you please have a look and advise which versions to use?

### PR DESCRIPTION
**Pull request by tiborsimko**
* Pins ATLAS base docker images which makes the workflow to produce
  plots again. (closes #21)

Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>

### CODE REVIEW

**Comment by tiborsimko** [comment]
Note: works locally with pure yadage, fails on REANA with:

```
WORKFLOW ENGINE LOGS
this is a tracking log at 2019-11-28T17:23:42.479891
this is a tracking log at 2019-11-28T17:23:43.934327
this is a tracking log at 2019-11-28T17:23:49.495323
this is a tracking log at 2019-11-28T17:23:54.824530
this is a tracking log at 2019-11-28T17:23:59.916665
workflow failed: workflow finished but failed



JOB LOGS
job id: 602fe7f7-9c7d-4ecd-84aa-01e4a7e89999
job:
 bash: line 1: /home/atlas/release_setup.sh: Permission denied
bash: line 4: recast_xsecs.txt: Permission denied
bash: line 9: recast_inputs.txt: Permission denied
myEventSelection: error while loading shared libraries: libEventLoop.so: cannot open shared object file: No such file or directory
```

**Comment by tiborsimko** [comment]
Note: the example works perfectly well if I force expected UID and GID values via `reana-commons`:

```diff
diff --git a/reana_commons/config.py b/reana_commons/config.py
index 7f8d620..c51f902 100644
--- a/reana_commons/config.py
+++ b/reana_commons/config.py
@@ -144,12 +144,12 @@ WORKFLOW_RUNTIME_USER_NAME = os.getenv(
 
 WORKFLOW_RUNTIME_USER_UID = os.getenv(
     'WORKFLOW_RUNTIME_USER_UID',
-    1000)
+    500)
 """Default user id for running job controller/workflow engine apps & jobs."""
 
 WORKFLOW_RUNTIME_USER_GID = os.getenv(
     'WORKFLOW_RUNTIME_USER_GID',
-    0)
+    500)
 """Default group id for running job controller/workflow engine apps & jobs."""
 
 REANA_USER_SECRET_MOUNT_PATH = os.getenv(
```

as expected by the environment image:

```console
$ docker run -i -t --rm reanahub/reana-demo-atlas-recast-eventselection /usr/bin/id
uid=500(atlas) gid=500(atlas) groups=500(atlas),0(root)
```

(1) We'd need an easy way for users to specify wanted UID/GID for their workflows steps e.g. in the workflow definition or in ``reana.yaml``... Alternatively (2) we could attempt to auto-discover UID/GID for each step by running `/usr/bin/id` in the container before each step... Muse IRL.

**Comment by tiborsimko** [comment]
Note: created an issue for proper UID/GID runtime setting, so this PR can be merged.

**Comment by roksys** [comment]
Can be tested with PRs referenced in reanahub/reana-workflow-controller/issues/269

```
$ git diff
diff --git a/workflow/steps.yml b/workflow/steps.yml
index c7165b9..66ae250 100644
--- a/workflow/steps.yml
+++ b/workflow/steps.yml
@@ -20,6 +20,8 @@ eventselection:
   environment:
     environment_type: 'docker-encapsulated'
     image: reanahub/reana-demo-atlas-recast-eventselection
+    resources:
+      - kubernetes_uid: 500
 
 statanalysis:
   process:
@@ -44,3 +46,5 @@ statanalysis:
   environment:
     environment_type: 'docker-encapsulated'
     image: reanahub/reana-demo-atlas-recast-statanalysis
+    resources:
+      - kubernetes_uid: 500
```

**Pull request merged**
